### ISSUE TITLE
Is it possible to change the source code format?

### ISSUE THREAD

**Issue by simplycomputing** [codepotent/Enriched-Editor#8]
In Joomla the TinyMCE source code is formatted in a more readable way...

![sourcecode](https://user-images.githubusercontent.com/46998578/71384910-4d973280-2638-11ea-90c4-97b9bd0e102d.jpg)

when compared to the Advanced Editor version...

![sourcecode2](https://user-images.githubusercontent.com/46998578/71384921-5e47a880-2638-11ea-8543-dd99d2fd69f5.jpg)

It may not be possible, but it would be nice to make the formatting a little better.

**Comment by johnalarcon** [comment]
Sorry for the delay, @simplycomputing, ...thought I'd responded to this. 😑 

While I do see the value in this, it's not planned for implementation. However, if someone were to write a PR for it, I'd be happy to get it in.
